apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: escale-api
    environnement: {{ .Values.environnement }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels: { app: escale-api }
  template:
    metadata:
      labels: { app: escale-api }
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports: [{ containerPort: 8000 }]
          envFrom:
            - configMapRef: { name: {{ .Release.Name }}-config }
          resources: {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet: { path: /healthz, port: 8000 }
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /readyz, port: 8000 }
            periodSeconds: 5
