apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  SERVICE_NAME: escale-api
  PORT: "8000"
  LOG_FORMAT: json
  LOG_LEVEL: {{ if eq .Values.environnement "prod" }}WARNING{{ else }}DEBUG{{ end }}
